version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '8080:8080'
    environment:
      DB_CONNECTION_URL: 'mongodb://db:27017'
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
